// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        info_body4: string;
        info_body4_1: string;
        info_body4_2: string;
        info_slug4: string;
        page4: string;
        page4_col1: string;
        page4_col2: string;
        page4_fill: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
