// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        clear: string;
        info: string;
        info_body1: string;
        info_slug1: string;
        notify_me: string;
        page1: string;
        page1_grid: string;
        picture1: string;
        picture1_fill: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
