// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        info_body2: string;
        info_slug2: string;
        page2: string;
        page2_col1: string;
        page2_col2: string;
        page2_fill: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
