// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        info_body5: string;
        info_slug5: string;
        page5: string;
        page5_col1: string;
        page5_col2: string;
        page5_fill: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
