// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        info_body3: string;
        info_body3_2: string;
        info_list3: string;
        info_slug3: string;
        page3: string;
        page3_col1: string;
        page3_col2: string;
        page3_fill: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
